### ISSUE TITLE
custom table prefix not reflecte

### ISSUE THREAD

**Issue by Spica2** [goldsky/UploadToUsers#2]
this table is generated:
modx_uploadtousers_addendum

and does not reflect custom prefixes like:
modx123_uploadtousers_addendum

does this cause any problems?

**Comment by goldsky** [comment]
yes, it is.
good catch,
i'll make a fix.

**Comment by goldsky** [comment]
fixed in here
https://github.com/goldsky/UploadToUsers/commit/6ab117649a5d7596a8b9a7c1e435e317d14dd4af#L26R52
